/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author vickysaldivia
 */
public class ValoresIniciales extends javax.swing.JFrame {

    
    public ValoresIniciales() {
        initComponents();
        //appleBase = (int) ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Volver1 = new javax.swing.JButton();
        RestantesEntrega = new javax.swing.JSpinner();
        DuracionDias = new javax.swing.JSpinner();
        AppleAssembler = new javax.swing.JSpinner();
        AppleBase = new javax.swing.JSpinner();
        AppleCPU = new javax.swing.JSpinner();
        AppleRAM = new javax.swing.JSpinner();
        ApplePSupply = new javax.swing.JSpinner();
        AppleGCard = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DellAssembler = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DellGCard = new javax.swing.JSpinner();
        DellPSupply = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DellRAM = new javax.swing.JSpinner();
        DellCPU = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DellBase = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIGURACIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 490, 50));

        Volver.setBackground(new java.awt.Color(0, 102, 204));
        Volver.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Guardar");
        Volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 100, 40));

        Volver1.setBackground(new java.awt.Color(0, 102, 204));
        Volver1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Volver1.setForeground(new java.awt.Color(255, 255, 255));
        Volver1.setText("Volver");
        Volver1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });
        jPanel1.add(Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 100, 40));

        RestantesEntrega.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        RestantesEntrega.setModel(new javax.swing.SpinnerNumberModel(30000, 0, 60000, 1));
        jPanel1.add(RestantesEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 130, -1));

        DuracionDias.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DuracionDias.setModel(new javax.swing.SpinnerNumberModel(1000, 0, 10000, 1));
        jPanel1.add(DuracionDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 130, -1));

        AppleAssembler.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AppleAssembler.setModel(new javax.swing.SpinnerNumberModel(2, 0, 20, 1));
        jPanel1.add(AppleAssembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, -1));

        AppleBase.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AppleBase.setModel(new javax.swing.SpinnerNumberModel(2, 0, 18, 1));
        jPanel1.add(AppleBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, -1));

        AppleCPU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AppleCPU.setModel(new javax.swing.SpinnerNumberModel(12, 0, 20, 1));
        jPanel1.add(AppleCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 130, -1));

        AppleRAM.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AppleRAM.setModel(new javax.swing.SpinnerNumberModel(2, 0, 20, 1));
        jPanel1.add(AppleRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, -1));

        ApplePSupply.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ApplePSupply.setModel(new javax.swing.SpinnerNumberModel(1, 0, 18, 1));
        jPanel1.add(ApplePSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, -1));

        AppleGCard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AppleGCard.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));
        jPanel1.add(AppleGCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 130, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("  Duración de días:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 340, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" Power Supply:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 309, 210, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(" Graphics Card:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 349, 190, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" CPU:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" Base Plate:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Trabajadores");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 250, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(" RAM:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 269, 190, 30));

        DellAssembler.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DellAssembler.setModel(new javax.swing.SpinnerNumberModel(1, 0, 18, 1));
        jPanel1.add(DellAssembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 130, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText(" Assembler:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 210, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText(" Graphics Card:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, 30));

        DellGCard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DellGCard.setModel(new javax.swing.SpinnerNumberModel(2, 0, 18, 1));
        jPanel1.add(DellGCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 130, -1));

        DellPSupply.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DellPSupply.setModel(new javax.swing.SpinnerNumberModel(1, 0, 18, 1));
        jPanel1.add(DellPSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 130, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText(" Power Supply:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 210, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(" RAM:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 190, 30));

        DellRAM.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DellRAM.setModel(new javax.swing.SpinnerNumberModel(2, 0, 20, 1));
        jPanel1.add(DellRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 130, -1));

        DellCPU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DellCPU.setModel(new javax.swing.SpinnerNumberModel(10, 0, 18, 1));
        jPanel1.add(DellCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 130, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText(" CPU:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 170, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText(" Base Plate:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 170, 30));

        DellBase.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DellBase.setModel(new javax.swing.SpinnerNumberModel(2, 0, 18, 1));
        jPanel1.add(DellBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 130, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Trabajadores");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 250, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText(" Assembler:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 210, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("  Días restantes para la entrega: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 280, 40));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 102, 204));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("DELL");
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jTextField5.setFocusable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 190, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jTextField4.setFocusable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 420, 70));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 102, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("APPLE");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jTextField2.setFocusable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 40));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jTextField3.setFocusable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 330));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jTextField6.setFocusable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 300, 330));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(231, 240, 249));
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jTextField1.setFocusable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Volver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoresIniciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoresIniciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AppleAssembler;
    private javax.swing.JSpinner AppleBase;
    private javax.swing.JSpinner AppleCPU;
    private javax.swing.JSpinner AppleGCard;
    private javax.swing.JSpinner ApplePSupply;
    private javax.swing.JSpinner AppleRAM;
    private javax.swing.JSpinner DellAssembler;
    private javax.swing.JSpinner DellBase;
    private javax.swing.JSpinner DellCPU;
    private javax.swing.JSpinner DellGCard;
    private javax.swing.JSpinner DellPSupply;
    private javax.swing.JSpinner DellRAM;
    private javax.swing.JSpinner DuracionDias;
    private javax.swing.JSpinner RestantesEntrega;
    private javax.swing.JButton Volver;
    private javax.swing.JButton Volver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
